server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

userManagementJwt:
  app:
    jwtSecret: Y29pbkFwcEpXVFNlY3JldEtleUZvckNBVEdU
    jwtExpirationMs: 3600000

userManagement:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080
